## 🌊 一、池化层的作用是啥？

池化层的主要目的是：

- **降低特征图的尺寸**（减少计算量）
- **保留主要特征**（对小的变形、偏移不敏感）
- **减少过拟合**

它不像卷积层那样“学参数”，池化层**没有可学习参数**，只是一种固定操作。

---

## 🔹 二、常见的池化方式

### 1. **最大池化（Max Pooling）**
取池化窗口中**最大的数**。

- 常用，提取最强的激活值。
- 对边缘、纹理特别敏感。

### 2. **平均池化（Average Pooling）**
取池化窗口中的**平均值**。

- 比较平滑，对整体感知有效。
- 现在不如最大池化常用。

### 3. **全局平均池化（Global Average Pooling）**
直接对**整张特征图**求平均（比如把 `7x7` 直接变成 `1x1`），通常用于分类的最后阶段。

---

## 🔹 三、池化计算举例

假设你有一个输入特征图是：

```
1 3 2 4  
5 6 1 2  
7 8 9 4  
4 5 2 1  
```

用 `2x2` 的最大池化，步长为 2（不重叠），窗口滑动方式如下：

- 第一个 `2x2`：`[1 3; 5 6]` → 最大值是 6  
- 第二个 `2x2`：`[2 4; 1 2]` → 最大值是 4  
- 第三个 `2x2`：`[7 8; 4 5]` → 最大值是 8  
- 第四个 `2x2`：`[9 4; 2 1]` → 最大值是 9  

最终输出是：

```
6 4  
8 9  
```

这就把 `4x4` 的图压缩成了 `2x2`。

---

## 🔹 四、输出尺寸计算公式

和卷积类似：

$$
\text{输出大小} = \left\lfloor \frac{输入大小 - 池化窗口大小}{步长} \right\rfloor + 1
$$

In [1]:
import torch
import torch.nn as nn

In [3]:
inputs = torch.tensor(data=[[[0, 1, 2], [3, 4, 5], [6, 7, 8]]], dtype=torch.float32)

# 创建池化层
pool = nn.MaxPool2d(kernel_size=(2, 2), stride=1, padding=0)
outputs = pool(inputs)
print(outputs)

tensor([[[4., 5.],
         [7., 8.]]])


In [4]:
pool = nn.AvgPool2d(kernel_size=(2, 2), stride=1, padding=0)
outputs = pool(inputs)
print(outputs)

tensor([[[2., 3.],
         [5., 6.]]])


In [6]:
inputs = torch.tensor([[[0, 1, 2], [3, 4, 5], [6, 7, 8]],
[[10, 20, 30], [40, 50, 60], [70, 80, 90]],
[[11, 22, 33], [44, 55, 66], [77, 88, 99]]], dtype=torch.float32)
print(inputs.shape)
pool = nn.MaxPool2d(kernel_size=(2, 2), stride=1, padding=0)
outputs = pool(inputs)
print(outputs)

torch.Size([3, 3, 3])
tensor([[[ 4.,  5.],
         [ 7.,  8.]],

        [[50., 60.],
         [80., 90.]],

        [[55., 66.],
         [88., 99.]]])
