In [1]:
import torch
import numpy as np

## 张量转换为numpy数组

In [2]:
t1 = torch.tensor([
    [1, 2, 3],
    [4, 5, 6]
])
t1

tensor([[1, 2, 3],
        [4, 5, 6]])

In [3]:
t1.dtype

torch.int64

In [4]:
n1 = t1.numpy()  # 转换之后共享内存, copy()函数不共享内存
n1

array([[1, 2, 3],
       [4, 5, 6]], dtype=int64)

In [5]:
n1.dtype

dtype('int64')

In [6]:
t1[0][0] = 100
t1

tensor([[100,   2,   3],
        [  4,   5,   6]])

In [7]:
n1

array([[100,   2,   3],
       [  4,   5,   6]], dtype=int64)

## numpy数组转化为张量

In [8]:
n1 = np.array([
    [
        [1, 2, 3],
        [4, 5, 6]
    ],
    [
        [7, 8, 9],
        [10, 11, 12]
    ]
])
t1 = torch.from_numpy(n1)  # 共享内存
t1

tensor([[[ 1,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)

In [9]:
n1[0][0][0] = 8

In [10]:
n1

array([[[ 8,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [11]:
t1

tensor([[[ 8,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)

In [12]:
t2 = torch.tensor(n1)  # 不共享内存
t2

tensor([[[ 8,  2,  3],
         [ 4,  5,  6]],

        [[ 7,  8,  9],
         [10, 11, 12]]], dtype=torch.int32)

In [13]:
t2[0][0][2] = 100
t2

tensor([[[  8,   2, 100],
         [  4,   5,   6]],

        [[  7,   8,   9],
         [ 10,  11,  12]]], dtype=torch.int32)

In [14]:
n1

array([[[ 8,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

## 标量张量和数字转换

In [15]:
t1 = torch.tensor(34)
t1


tensor(34)

In [16]:
t1.item()

34

In [17]:
torch.tensor(23).item()

23