In [1]:
import torch

In [3]:
# add、sub、mul、div、neg
# add_、sub_、mul_、div_、neg_（其中带下划线的版本会修改原数据）

In [2]:
t1 = torch.tensor(data=[1, 2, 3, 4])

In [3]:
t2 = t1 + 3
t2

tensor([4, 5, 6, 7])

In [4]:
t3 = t1 + t2
t3

tensor([ 5,  7,  9, 11])

In [5]:
-t1

tensor([-1, -2, -3, -4])

In [7]:
torch.add(input=t1, other=2)

tensor([3, 4, 5, 6])

In [8]:
t1.neg_()

tensor([-1, -2, -3, -4])

In [9]:
t1

tensor([-1, -2, -3, -4])

In [10]:
t1 = torch.tensor([
    [1, 2],
    [3, 4]
])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

In [11]:
t1 * t2  # Hadamard乘积，也称作元素级乘法（Element-wise product），是矩阵或数组对应元素相乘得到的结果

tensor([[ 5, 12],
        [21, 32]])

In [12]:
torch.mul(t1, t2)

tensor([[ 5, 12],
        [21, 32]])

In [13]:
torch.multiply(t1, t2)

tensor([[ 5, 12],
        [21, 32]])

In [14]:
torch.matmul(t1, t2)

tensor([[19, 22],
        [43, 50]])

In [15]:
t1@t2

tensor([[19, 22],
        [43, 50]])

In [2]:
t1 = torch.tensor([1, 2])
t2 = torch.tensor([
    [5, 6],
    [7, 8]
])

In [17]:
t1 * t2

tensor([[ 5, 12],
        [ 7, 16]])

In [18]:
torch.multiply(t1, t2)

tensor([[ 5, 12],
        [ 7, 16]])

In [19]:
torch.matmul(t1, t2)

tensor([19, 22])

In [20]:
t1@t2

tensor([19, 22])

In [21]:
t1 = torch.tensor([1, 2])
t2 = torch.tensor([3, 4])

In [22]:
torch.dot(t1, t2)

tensor(11)

In [23]:
t1@t2

tensor(11)