In [1]:
import torch

In [2]:
t1 = torch.tensor(data=[
    [1., 2, 3, 4],
    [5, 6, 7, 8]
])

In [3]:
t1.mean()

tensor(4.5000)

In [4]:
t1.mean(dim=0)  # 按列运算

tensor([3., 4., 5., 6.])

In [5]:
t1.mean(dim=1)  # 按行运算

tensor([2.5000, 6.5000])

In [6]:
t1.sum()

tensor(36.)

In [7]:
t1.sum(dim=0)

tensor([ 6.,  8., 10., 12.])

In [8]:
t1.sum(dim=1)

tensor([10., 26.])

In [9]:
t1.sqrt()  # 开方

tensor([[1.0000, 1.4142, 1.7321, 2.0000],
        [2.2361, 2.4495, 2.6458, 2.8284]])

In [10]:
torch.sqrt(input=t1)

tensor([[1.0000, 1.4142, 1.7321, 2.0000],
        [2.2361, 2.4495, 2.6458, 2.8284]])

In [11]:
t1.pow(2)  # 幂次方运算

tensor([[ 1.,  4.,  9., 16.],
        [25., 36., 49., 64.]])

In [12]:
torch.pow(input=t1, exponent=3)

tensor([[  1.,   8.,  27.,  64.],
        [125., 216., 343., 512.]])

In [13]:
t1.exp()  # e^x 张量的元素值为x

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03]])

In [14]:
torch.exp(input=t1)

tensor([[2.7183e+00, 7.3891e+00, 2.0086e+01, 5.4598e+01],
        [1.4841e+02, 4.0343e+02, 1.0966e+03, 2.9810e+03]])

In [15]:
t1.log()

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794]])

In [16]:
torch.log(input=t1)  # 默认以e为底

tensor([[0.0000, 0.6931, 1.0986, 1.3863],
        [1.6094, 1.7918, 1.9459, 2.0794]])

In [17]:
t1.log2()

tensor([[0.0000, 1.0000, 1.5850, 2.0000],
        [2.3219, 2.5850, 2.8074, 3.0000]])

In [18]:
t1.log10()

tensor([[0.0000, 0.3010, 0.4771, 0.6021],
        [0.6990, 0.7782, 0.8451, 0.9031]])

In [19]:
torch.log2(input=t1)

tensor([[0.0000, 1.0000, 1.5850, 2.0000],
        [2.3219, 2.5850, 2.8074, 3.0000]])