In [1]:
import torch

In [2]:
torch.manual_seed(22)
data = torch.randint(low=2, high=10, size=(4, 5))
data

tensor([[7, 6, 6, 2, 6],
        [8, 8, 5, 6, 2],
        [9, 6, 7, 4, 8],
        [6, 7, 2, 4, 7]])

In [16]:
data[0]

tensor([7, 6, 6, 2, 6])

In [17]:
data[:, 0]

tensor([7, 8, 9, 6])

In [31]:
data[1, 2]

tensor(5)

In [23]:
data[3, 4]

tensor(7)

In [24]:
data[[1, 3], [2, 4]] # 第一行第二列 和 第三行第四列的元素

tensor([5, 7])

In [32]:
data[[[1], [3]], [2, 4]]

tensor([5, 7])

In [38]:
data[:, 1] > 6

tensor([False,  True, False,  True])

In [37]:
data[data[:, 1] > 6]

tensor([[8, 8, 5, 6, 2],
        [6, 7, 2, 4, 7]])

In [42]:
data[2] > 6

tensor([ True, False,  True, False,  True])

In [41]:
data[:, data[2] > 6]

tensor([[7, 6, 6],
        [8, 5, 2],
        [9, 7, 8],
        [6, 2, 7]])

In [43]:
data[::2, 1::2]

tensor([[6, 2],
        [6, 4]])

In [4]:
data = torch.randint(0, 10, size=(3, 4, 5))  # 三维张量
data

tensor([[[3, 2, 9, 7, 8],
         [4, 1, 7, 9, 6],
         [8, 1, 6, 1, 0],
         [3, 5, 3, 8, 5]],

        [[7, 7, 5, 1, 8],
         [8, 9, 5, 5, 2],
         [9, 0, 5, 6, 7],
         [9, 1, 3, 7, 5]],

        [[1, 7, 4, 9, 0],
         [0, 5, 1, 7, 3],
         [9, 7, 6, 5, 7],
         [9, 0, 7, 0, 1]]])

In [5]:
data[0, :, :]

tensor([[3, 2, 9, 7, 8],
        [4, 1, 7, 9, 6],
        [8, 1, 6, 1, 0],
        [3, 5, 3, 8, 5]])

In [6]:
data[:, 0, :]

tensor([[3, 2, 9, 7, 8],
        [7, 7, 5, 1, 8],
        [1, 7, 4, 9, 0]])

In [7]:
data[:, :, 0]

tensor([[3, 4, 8, 3],
        [7, 8, 9, 9],
        [1, 0, 9, 9]])