In [2]:
import torch

## shape函数

In [3]:
torch.manual_seed(0)
data = torch.randint(0, 10, size=(5, 6))
data

tensor([[4, 9, 3, 0, 3, 9],
        [7, 3, 7, 3, 1, 6],
        [6, 9, 8, 6, 6, 8],
        [4, 3, 6, 9, 1, 4],
        [4, 1, 9, 9, 9, 0]])

In [4]:
# reshape 修改连续或非连续张量的形状, 不改数据
data.reshape(shape=(2, 15))

tensor([[4, 9, 3, 0, 3, 9, 7, 3, 7, 3, 1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3, 6, 9, 1, 4, 4, 1, 9, 9, 9, 0]])

In [5]:
data.reshape(shape=(-1, 15))  # -1 会自动计算

tensor([[4, 9, 3, 0, 3, 9, 7, 3, 7, 3, 1, 6, 6, 9, 8],
        [6, 6, 8, 4, 3, 6, 9, 1, 4, 4, 1, 9, 9, 9, 0]])

## squeeze和unsqueeze函数

In [6]:
# squeeze 指定需要压缩的维度（该维度必须大小为1）。如果不指定，则去掉所有维度大小为1的维度。
# unsqueeze 在指定位置插入一个大小为1的新维度。
# 维度的大小（dimension size）是指张量（Tensor）或数组（Array）在某一个维度上的元素个数。

In [7]:
data = torch.randint(0, 10, size=(3, 1, 2, 1))
data

tensor([[[[1],
          [2]]],


        [[[3],
          [0]]],


        [[[5],
          [5]]]])

In [8]:
data.shape

torch.Size([3, 1, 2, 1])

In [9]:
torch.squeeze(input=data)

tensor([[1, 2],
        [3, 0],
        [5, 5]])

In [10]:
torch.squeeze(input=data, dim=1).shape

torch.Size([3, 2, 1])

In [11]:
torch.squeeze(input=data, dim=2).shape

torch.Size([3, 1, 2, 1])

In [12]:
torch.squeeze(input=data, dim=3).shape

torch.Size([3, 1, 2])

In [13]:
data = torch.randint(0, 10, size=(3, 2))
data

tensor([[2, 9],
        [1, 8],
        [8, 3]])

In [14]:
data.unsqueeze(dim=2).shape

torch.Size([3, 2, 1])

In [15]:
data.unsqueeze(dim=0).shape

torch.Size([1, 3, 2])

In [16]:
data.unsqueeze(dim=-1).shape

torch.Size([3, 2, 1])

## transpose和permute函数

In [17]:
# permute 改变张量任意维度顺序
# transpose 改变张量两个维度的顺序
data = torch.randint(0, 10, size=(3, 4, 5))
data

tensor([[[6, 9, 1, 7, 3],
         [5, 2, 1, 0, 9],
         [3, 1, 1, 0, 3],
         [6, 6, 7, 9, 6]],

        [[3, 4, 5, 0, 8],
         [2, 8, 2, 7, 5],
         [0, 0, 8, 1, 9],
         [6, 1, 0, 2, 9]],

        [[4, 3, 9, 3, 9],
         [3, 9, 8, 5, 3],
         [2, 8, 5, 6, 6],
         [5, 7, 2, 5, 6]]])

In [18]:
data.shape

torch.Size([3, 4, 5])

In [19]:
data.transpose(dim0=1, dim1=0).shape

torch.Size([4, 3, 5])

In [20]:
data.permute(dims=(1, 2, 0)).shape

torch.Size([4, 5, 3])

## view和contiguous函数

In [21]:
# 一个 contiguous（连续） 的张量意味着它在内存中的元素是按照 行优先（C-style）顺序排列 的，中间没有跳跃、重排。
# view() 修改连续张量的形状, 和reshape类似
data = torch.randint(0, 10, size=(3, 4))
data

tensor([[6, 5, 4, 0],
        [8, 1, 7, 8],
        [5, 4, 4, 8]])

In [22]:
data.is_contiguous()

True

In [23]:
data.view(2, 6).shape

torch.Size([2, 6])

In [24]:
data.view(2, 6).is_contiguous()

True

In [25]:
data.transpose(1, 0).shape

torch.Size([4, 3])

In [26]:
data.transpose(1, 0).is_contiguous()

False

In [27]:
data.transpose(1, 0).contiguous().is_contiguous()

True

In [30]:
data.reshape(4, 3).is_contiguous()

True