In [11]:
import torch

## cat 函数

In [12]:
# cat 在指定的维度上进行拼接, 其他维度值必须相同
torch.manual_seed(0)
t1 = torch.randint(0, 10, size=(2, 3))
t2 = torch.randint(0, 10, size=(2, 3))

In [13]:
t1

tensor([[4, 9, 3],
        [0, 3, 9]])

In [14]:
t2

tensor([[7, 3, 7],
        [3, 1, 6]])

In [15]:
torch.cat(tensors=(t1, t2), dim=0)

tensor([[4, 9, 3],
        [0, 3, 9],
        [7, 3, 7],
        [3, 1, 6]])

In [16]:
torch.cat(tensors=(t1, t2), dim=1)

tensor([[4, 9, 3, 7, 3, 7],
        [0, 3, 9, 3, 1, 6]])

## stack 函数

In [17]:
# torch.stack 是 PyTorch 中用于将一组张量沿着一个新维度进行拼接（stack）的函数。它和 torch.cat（按已有维度拼接）不同的是：torch.stack 会新增一个维度。
torch.stack(tensors=[t1, t2], dim=0)

tensor([[[4, 9, 3],
         [0, 3, 9]],

        [[7, 3, 7],
         [3, 1, 6]]])

In [18]:
torch.stack(tensors=[t1, t2], dim=0).shape

torch.Size([2, 2, 3])

In [19]:
torch.stack(tensors=(t1, t2, t1), dim=0)

tensor([[[4, 9, 3],
         [0, 3, 9]],

        [[7, 3, 7],
         [3, 1, 6]],

        [[4, 9, 3],
         [0, 3, 9]]])