In [1]:
import torch

In [3]:
w = torch.tensor(data=10, requires_grad=True, dtype=torch.float32)
for i in range(1, 1001):
    loss = w ** 2 + 20
    if w.grad is not None:
        w.grad.zero_()
    loss.backward()
    w.data = w.data - 0.1 * w.grad  # 更新w张量对象的数据, 不能直接使用w.
print(w, w.grad, loss)

tensor(2.8026e-45, requires_grad=True) tensor(5.6052e-45) tensor(20., grad_fn=<AddBackward0>)


In [24]:
# 不能将自动微分的张量转换成numpy数组，会发生报错，可以通过detach()方法实现
t1 = torch.tensor(data=[1, 2, 3], requires_grad=True, dtype=torch.float16)
t1

tensor([1., 2., 3.], dtype=torch.float16, requires_grad=True)

In [25]:
t1.numpy()

RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.

In [26]:
t2 = t1.detach()
t2  # t1 和 t2共享数据, 但t2不会自动微分|

tensor([1., 2., 3.], dtype=torch.float16)

In [27]:
t2.requires_grad

False

In [29]:
t2[0] = 999

In [30]:
t1[0]

tensor(999., dtype=torch.float16, grad_fn=<SelectBackward0>)

In [22]:
t2.numpy()  # 现在可以转为numpy数组

array([1., 2., 3.], dtype=float16)