In [1]:
import torch
import torch.nn as nn

In [ ]:
linear1 = nn.Linear(in_features=5, out_features=8)

# 从0-1均匀分布产生参数
nn.init.uniform_(linear1.weight)
nn.init.uniform_(linear1.bias)
print(linear1.weight)
print(linear1.bias)

# input 的形状是 [batch_size, in_features]
# weight 是 [out_features, in_features]
# input @ weight.T 的形状就变成 [batch_size, out_features]

Parameter containing:
tensor([[0.9727, 0.1492, 0.4107, 0.4992, 0.8098],
        [0.1534, 0.4749, 0.0061, 0.6802, 0.9307],
        [0.3120, 0.9407, 0.0378, 0.7331, 0.9200],
        [0.0402, 0.9639, 0.9302, 0.5560, 0.2149],
        [0.5966, 0.1667, 0.3100, 0.8579, 0.2599],
        [0.7714, 0.5693, 0.6886, 0.8572, 0.5082],
        [0.7550, 0.5557, 0.0120, 0.6322, 0.1537],
        [0.6742, 0.5447, 0.2144, 0.9890, 0.5172]], requires_grad=True)
Parameter containing:
tensor([0.8080, 0.7661, 0.6391, 0.0882, 0.4132, 0.1787, 0.9444, 0.8040],
       requires_grad=True)


In [5]:
linear2 = nn.Linear(in_features=8, out_features=3)

# 正态分布随机初始化
nn.init.normal_(linear2.weight)
nn.init.normal_(linear2.bias)
print(linear2.weight)
print(linear2.bias)

Parameter containing:
tensor([[-1.0592, -0.5504, -0.1258, -0.3683,  1.8651, -0.8862, -0.9418, -0.8276],
        [ 0.8580, -1.7136,  0.3904, -0.2263, -0.9812, -0.6520, -0.6145,  0.0535],
        [-0.5074, -0.0674,  0.9180, -0.7933,  1.2023,  1.2862, -1.9546,  0.6695]],
       requires_grad=True)
Parameter containing:
tensor([ 0.0231,  0.5643, -0.8275], requires_grad=True)


In [ ]:
# Sigmoid/Tanh：Xavier 初始化
# ReLU/Leaky ReLU：kaiming 初始化
# 网络的深度
# 浅层网络：随机初始化即可
# 深层网络：需要考虑方差平衡，如 Xavier 或 kaiming 初始化