### 🧠 核心思想

> **AdaGrad 让每个参数都有自己独立的学习率，并且这个学习率会随训练过程动态调整。**

它的目标是：
- **自动调节学习率**
- **适应稀疏数据或不均衡特征**
- **防止某些参数更新太快或太慢**

---

### 🔍 数学公式

设：
- $ \theta $：模型参数
- $ g_t $：当前梯度
- $ G_t $：历史梯度平方的累加

AdaGrad 的更新公式为：

$$
G_t = G_{t-1} + g_t^2
$$
$$
\theta_{t+1} = \theta_t - \frac{\eta}{\sqrt{G_t} + \epsilon} \cdot g_t
$$

其中：
- $ \eta $：初始学习率
- $ \epsilon $：防止除以 0 的小常数（如 $10^{-8}$）

👉 由于 $ G_t $ 会不断增大，**分母变大 → 实际学习率变小**，所以：
- 梯度较大的参数更新幅度变小
- 梯度较小的参数可以更新得更多

---

### 📈 AdaGrad 的优缺点

| ✅ 优点 | ❌ 缺点 |
|--------|--------|
| 自动调节学习率 | 学习率会越来越小，可能提前“停止学习” |
| 适合稀疏数据（如 NLP） | 在非稀疏任务中容易下降太快而停滞 |
| 易实现、收敛稳定 | 无法“恢复”学习率 |


In [1]:
import torch
from torch import optim

w = torch.tensor(data=[1.0], requires_grad=True, dtype=torch.float32)
optimizer = optim.Adagrad(params=[w], lr=0.01)

for i in range(10):
    loss = (w**2)/2.0
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(w.grad, w, loss)

tensor([1.]) tensor([0.9900], requires_grad=True) tensor([0.5000], grad_fn=<DivBackward0>)
tensor([0.9900]) tensor([0.9830], requires_grad=True) tensor([0.4901], grad_fn=<DivBackward0>)
tensor([0.9830]) tensor([0.9772], requires_grad=True) tensor([0.4831], grad_fn=<DivBackward0>)
tensor([0.9772]) tensor([0.9723], requires_grad=True) tensor([0.4775], grad_fn=<DivBackward0>)
tensor([0.9723]) tensor([0.9679], requires_grad=True) tensor([0.4727], grad_fn=<DivBackward0>)
tensor([0.9679]) tensor([0.9638], requires_grad=True) tensor([0.4684], grad_fn=<DivBackward0>)
tensor([0.9638]) tensor([0.9601], requires_grad=True) tensor([0.4645], grad_fn=<DivBackward0>)
tensor([0.9601]) tensor([0.9567], requires_grad=True) tensor([0.4609], grad_fn=<DivBackward0>)
tensor([0.9567]) tensor([0.9534], requires_grad=True) tensor([0.4576], grad_fn=<DivBackward0>)
tensor([0.9534]) tensor([0.9503], requires_grad=True) tensor([0.4545], grad_fn=<DivBackward0>)
