
### 🧠 核心思想

回顾一下 AdaGrad 的问题：

- 它会把所有历史梯度平方累加，导致分母越来越大，**学习率越来越小，训练容易提前停滞**。

RMSprop 的思路是：

> **不用累加历史梯度的总和，而是对历史梯度做**指数加权平均（Exponential Moving Average）。

---

### 🔍 公式

设：
- $ g_t $：当前梯度
- $ E[g^2]_t $：梯度平方的滑动平均
- $ \gamma $：衰减率（常用值为 0.9）
- $ \eta $：学习率

RMSprop 的更新规则：

$$
E[g^2]_t = \gamma E[g^2]_{t-1} + (1 - \gamma) g_t^2
$$
$$
\theta_{t+1} = \theta_t - \frac{\eta}{\sqrt{E[g^2]_t} + \epsilon} \cdot g_t
$$

> 相当于：**让学习率对过去梯度“有记忆但逐渐遗忘”，保持动态而不会过早变小。**

---

### 📈 RMSprop 的优缺点

| ✅ 优点 | ❌ 缺点 |
|--------|--------|
| 适合非凸问题，收敛更稳 | 没有动量项（比 Adam 稍逊） |
| 避免学习率过快衰减 | 仍需调参（lr, alpha） |
| 表现比 AdaGrad 更强大 | 有时不如 Adam 一致稳定 |


In [2]:
import torch
from torch import optim

w = torch.tensor(data=[1.0], requires_grad=True, dtype=torch.float32)
optimizer = optim.RMSprop(params=[w], lr=0.01, alpha=0.9)

for i in range(10):
    loss = (w**2)/2.0
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(w.grad, w, loss)

tensor([1.]) tensor([0.9684], requires_grad=True) tensor([0.5000], grad_fn=<DivBackward0>)
tensor([0.9684]) tensor([0.9458], requires_grad=True) tensor([0.4689], grad_fn=<DivBackward0>)
tensor([0.9458]) tensor([0.9271], requires_grad=True) tensor([0.4473], grad_fn=<DivBackward0>)
tensor([0.9271]) tensor([0.9105], requires_grad=True) tensor([0.4297], grad_fn=<DivBackward0>)
tensor([0.9105]) tensor([0.8955], requires_grad=True) tensor([0.4145], grad_fn=<DivBackward0>)
tensor([0.8955]) tensor([0.8815], requires_grad=True) tensor([0.4010], grad_fn=<DivBackward0>)
tensor([0.8815]) tensor([0.8683], requires_grad=True) tensor([0.3885], grad_fn=<DivBackward0>)
tensor([0.8683]) tensor([0.8558], requires_grad=True) tensor([0.3770], grad_fn=<DivBackward0>)
tensor([0.8558]) tensor([0.8437], requires_grad=True) tensor([0.3662], grad_fn=<DivBackward0>)
tensor([0.8437]) tensor([0.8321], requires_grad=True) tensor([0.3559], grad_fn=<DivBackward0>)
