## ⚙️ Adam 优化算法简介

> **Adam = Momentum + RMSprop 的结合体**

它既考虑了：
- 一阶动量（梯度的均值）
- 二阶动量（梯度的平方均值）

并通过自适应学习率，使参数更新更加高效、鲁棒。

---

### 🔍 公式解析

Adam 维护两个滑动平均：

- **一阶矩估计（动量）**：
  $$
  m_t = \beta_1 m_{t-1} + (1 - \beta_1) g_t
  $$
- **二阶矩估计（RMS）**：
  $$
  v_t = \beta_2 v_{t-1} + (1 - \beta_2) g_t^2
  $$

再进行偏差修正（避免前几步趋近于 0）：

$$
\hat{m}_t = \frac{m_t}{1 - \beta_1^t},\quad \hat{v}_t = \frac{v_t}{1 - \beta_2^t}
$$

最后更新参数：

$$
\theta_{t+1} = \theta_t - \frac{\eta}{\sqrt{\hat{v}_t} + \epsilon} \cdot \hat{m}_t
$$

---

### 📈 优缺点总结

| ✅ 优点 | ❌ 缺点 |
|--------|--------|
| 收敛快，适用于大多数问题 | 有时泛化性能不如 SGD |
| 几乎不需要调参 | 容易“过拟合”局部最优 |
| 自动调节每个参数的学习率 | 参数更新机制略复杂 |
| 特别适合稀疏梯度场景（NLP） | |

---

In [4]:
import torch
from torch import optim

w = torch.tensor(data=[1.0], requires_grad=True, dtype=torch.float32)
optimizer = optim.Adam(params=[w], lr=0.01, betas=(0.9, 0.99))

for i in range(10):
    loss = (w**2)/2.0
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    print(w.grad, w, loss)

tensor([1.]) tensor([0.9900], requires_grad=True) tensor([0.5000], grad_fn=<DivBackward0>)
tensor([0.9900]) tensor([0.9800], requires_grad=True) tensor([0.4901], grad_fn=<DivBackward0>)
tensor([0.9800]) tensor([0.9700], requires_grad=True) tensor([0.4802], grad_fn=<DivBackward0>)
tensor([0.9700]) tensor([0.9600], requires_grad=True) tensor([0.4705], grad_fn=<DivBackward0>)
tensor([0.9600]) tensor([0.9500], requires_grad=True) tensor([0.4608], grad_fn=<DivBackward0>)
tensor([0.9500]) tensor([0.9401], requires_grad=True) tensor([0.4513], grad_fn=<DivBackward0>)
tensor([0.9401]) tensor([0.9301], requires_grad=True) tensor([0.4419], grad_fn=<DivBackward0>)
tensor([0.9301]) tensor([0.9202], requires_grad=True) tensor([0.4326], grad_fn=<DivBackward0>)
tensor([0.9202]) tensor([0.9102], requires_grad=True) tensor([0.4234], grad_fn=<DivBackward0>)
tensor([0.9102]) tensor([0.9003], requires_grad=True) tensor([0.4143], grad_fn=<DivBackward0>)
